FROM alpine:3.20

ARG TARGETPLATFORM

# 安装时区数据
RUN apk add --no-cache tzdata
ENV TZ=Asia/Shanghai

RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app
COPY ${TARGETPLATFORM}/telenotion-bot /app/telenotion-bot

ENTRYPOINT ["/app/telenotion-bot"]
