FROM alpine:3.20

ARG TARGETPLATFORM

RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app
COPY ${TARGETPLATFORM}/telenotion-bot /app/telenotion-bot

ENTRYPOINT ["/app/telenotion-bot"]
